[build]
  publish = "."

[build.environment]
  NODE_VERSION = "18"

# Form settings
[[forms]]
  name = "order-form"

[[forms]]
  name = "contact-form"

# Build settings
[build.processing.html]
  pretty_urls = true

# HTML Email notifications for order form
[[notifications]]
  type = "email"
  event = "submission-created"
  form = "order-form"
  to = ["mrdj78976@gmail.com"]
  subject = "🚨 NEW ORDER - Classic Carry - {{orderTotal}}"
  body = """
<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: Arial, sans-serif; background: #f7fafc; padding: 20px; margin: 0; }
        .container { max-width: 650px; margin: 0 auto; background: white; border-radius: 10px; overflow: hidden; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }
        .header { background: #2d3748; color: white; padding: 25px; text-align: center; }
        .alert { background: #fed7d7; border: 2px solid #feb2b2; color: #742a2a; padding: 20px; margin: 20px; border-radius: 8px; text-align: center; font-weight: bold; }
        .section { margin: 20px; padding: 20px; border-radius: 8px; }
        .customer-info { background: #e6fffa; border-left: 5px solid #38b2ac; }
        .order-details { background: #f7fafc; border-left: 5px solid #D2C1B6; }
        .financial { background: #fff5f5; border-left: 5px solid #f56565; }
        table { width: 100%; border-collapse: collapse; margin: 15px 0; }
        td { padding: 10px; border-bottom: 1px solid #e2e8f0; }
        .highlight { background: #D2C1B6; color: #2d3748; padding: 15px; border-radius: 6px; font-family: monospace; }
        .total { font-size: 18px; font-weight: bold; color: #D2C1B6; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🚨 NEW ORDER RECEIVED</h1>
            <p>Classic Carry - Order Management</p>
            <p style="font-size: 14px; opacity: 0.8;">{{orderDate}}</p>
        </div>
        
        <div class="alert">
            ⚡ ACTION REQUIRED: Process this order immediately!
        </div>
        
        <div class="section customer-info">
            <h3>👤 Customer Information</h3>
            <table>
                <tr><td><strong>Name:</strong></td><td>{{firstName}} {{lastName}}</td></tr>
                <tr><td><strong>Email:</strong></td><td>{{email}}</td></tr>
                <tr><td><strong>Phone:</strong></td><td>{{phone}}</td></tr>
            </table>
            
            <h4>📍 Delivery Address:</h4>
            <div style="background: white; padding: 15px; border-radius: 6px;">
                {{address}}<br>
                {{city}}, {{province}} {{postalCode}}
            </div>
            
            <h4>📝 Special Instructions:</h4>
            <div style="background: white; padding: 15px; border-radius: 6px; font-style: italic;">
                {{deliveryNotes}}
            </div>
        </div>
        
        <div class="section order-details">
            <h3>📦 Items to Prepare</h3>
            <div class="highlight">
                {{orderItems}}
            </div>
        </div>
        
        <div class="section financial">
            <h3>💰 Financial Summary</h3>
            <table>
                <tr><td>Subtotal:</td><td style="text-align: right; font-weight: bold;">{{orderSubtotal}}</td></tr>
                <tr><td>Delivery Charge:</td><td style="text-align: right; font-weight: bold;">{{orderDeliveryCharge}}</td></tr>
                <tr style="border-top: 2px solid #f56565;"><td><strong>TOTAL:</strong></td><td style="text-align: right;" class="total">{{orderTotal}}</td></tr>
            </table>
        </div>
        
        <div style="background: #2d3748; color: white; padding: 20px; text-align: center;">
            <p style="margin: 0; font-size: 14px;">
                <strong>Classic Carry Order Management</strong><br>
                Process orders promptly for customer satisfaction
            </p>
        </div>
    </div>
</body>
</html>
"""

# Customer confirmation email with HTML
[[notifications]]
  type = "email"
  event = "submission-created"
  form = "order-form"
  to = ["{{email}}"]
  subject = "✅ Order Confirmation - Classic Carry"
  body = """
<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; margin: 0; padding: 20px; background: #f5f5f5; }
        .container { max-width: 600px; margin: 0 auto; background: white; border-radius: 10px; overflow: hidden; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }
        .header { background: linear-gradient(135deg, #D2C1B6, #e2c9b8); padding: 30px; text-align: center; }
        .header h1 { color: #2d3748; margin: 0; font-size: 28px; }
        .content { padding: 30px; }
        .section { margin: 25px 0; padding: 20px; border-radius: 8px; }
        .order-summary { background: #f7fafc; border-left: 4px solid #D2C1B6; }
        .delivery-info { background: #e6fffa; border-left: 4px solid #38b2ac; }
        .next-steps { background: #fff5f5; border-left: 4px solid #f56565; }
        .footer { background: #2d3748; color: white; padding: 20px; text-align: center; }
        .status-badge { background: #48bb78; color: white; padding: 8px 16px; border-radius: 20px; font-size: 14px; font-weight: bold; display: inline-block; }
        table { width: 100%; border-collapse: collapse; margin: 15px 0; }
        td { padding: 8px 0; border-bottom: 1px solid #e2e8f0; }
        .total-row { border-top: 2px solid #D2C1B6; font-weight: bold; font-size: 16px; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>✨ Classic Carry</h1>
            <p style="margin: 10px 0 0 0; color: #4a5568; font-size: 16px;">Premium Caps & Wallets</p>
        </div>
        
        <div class="content">
            <div style="text-align: center; margin-bottom: 30px;">
                <span class="status-badge">✅ Order Confirmed</span>
            </div>
            
            <h2 style="color: #2d3748; margin-top: 0;">Dear {{firstName}} {{lastName}},</h2>
            <p>Thank you for your order! We're excited to get your premium items to you.</p>
            
            <div class="section order-summary">
                <h3 style="margin-top: 0; color: #2d3748;">📦 Order Summary</h3>
                <p><strong>Order Date:</strong> {{orderDate}}</p>
                
                <div style="background: white; padding: 15px; border-radius: 6px; margin: 15px 0;">
                    <h4 style="margin-top: 0; color: #2d3748;">Items Ordered:</h4>
                    <p style="font-family: monospace; background: #f7fafc; padding: 10px; border-radius: 4px;">{{orderItems}}</p>
                </div>
                
                <table>
                    <tr><td>Subtotal:</td><td style="text-align: right;">{{orderSubtotal}}</td></tr>
                    <tr><td>Delivery Charge:</td><td style="text-align: right;">{{orderDeliveryCharge}}</td></tr>
                    <tr class="total-row"><td>Total Amount:</td><td style="text-align: right; color: #D2C1B6;">{{orderTotal}}</td></tr>
                </table>
            </div>
            
            <div class="section delivery-info">
                <h3 style="margin-top: 0; color: #2d3748;">🚚 Delivery Details</h3>
                <p><strong>Delivery Address:</strong><br>
                {{address}}<br>
                {{city}}, {{province}} {{postalCode}}</p>
                
                <p><strong>Contact Phone:</strong> {{phone}}</p>
            </div>
            
            <div class="section next-steps">
                <h3 style="margin-top: 0; color: #2d3748;">📋 What Happens Next?</h3>
                <div style="display: flex; flex-direction: column; gap: 10px;">
                    <div>✅ <strong>Order Processing:</strong> 1-2 business days</div>
                    <div>📦 <strong>Packaging:</strong> Items carefully prepared</div>
                    <div>🚚 <strong>Shipping:</strong> 3-5 business days delivery</div>
                    <div>📧 <strong>Tracking:</strong> You'll receive tracking information</div>
                </div>
            </div>
            
            <div style="background: #e6fffa; padding: 20px; border-radius: 8px; text-align: center; margin: 25px 0;">
                <h3 style="margin-top: 0; color: #2d3748;">💬 Need Help?</h3>
                <p><strong>Phone:</strong> +92 316 092 8206<br>
                <strong>Email:</strong> support@classiccarry.com</p>
            </div>
        </div>
        
        <div class="footer">
            <h3 style="margin-top: 0;">Thank You for Choosing Classic Carry!</h3>
            <p style="margin-bottom: 0; font-size: 14px; opacity: 0.9;">
                Premium quality, delivered with care.
            </p>
        </div>
    </div>
</body>
</html>
"""

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"