[build]
  publish = "."

[build.environment]
  NODE_VERSION = "18"

# Form settings
[[forms]]
  name = "order-form"

[[forms]]
  name = "contact-form"

# Build settings - Use Netlify Dashboard for email notifications (more reliable)
[build.processing.html]
  pretty_urls = true

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"